name: flutter_application_2
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.2.0
  auto_route_generator: ^8.0.0
  build: ^2.4.1
  runner: ^1.0.3
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.4
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  meta:
  google_maps_flutter: ^2.2.8
  yandex_mapkit: ^4.1.0
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

